SAMPLES = ['Sample1', 'Sample2', 'Sample3']

dataPath = "data/"
resultPath = "results/"

rule all:
    input:
        'test.txt'

rule quantify_genes:
    input:
        genome = dataPath + 'reference.fa',
        r1 = 'fastq/{sample}.R1.fastq.gz',
        r2 = 'fastq/{sample}.R2.fastq.gz',
        r3 = 'fastq/{sample}.R3.fastq.gz'
    output:
        resultPath + '{sample}.txt'
    shell:
        'echo {input.genome} {input.r1} {input.r2} {input.r3} > {output}'


rule collate_outputs:
    input:
        expand(resultPath + '{sample}.txt', sample=SAMPLES)
    output:
        resultPath + 'test.txt'
    run:
        with open(output[0], 'w') as out:
            for i in input:
                sample = i.split('.')[0]
                for line in open(i):
                    out.write(sample + ' ' + line)

rule clean:
    shell:
        'rm' + resultPath + '*.txt'
