SAMPLES = ['Sample1', 'Sample2', 'Sample3']

result_folder = 'results'

rule all:
    input:
        expand(result_folder + '/{sample}.txt', sample = SAMPLES)

rule quantify_genes:
    input:
        genome = 'data/genome.fa',
        r1 = 'data/{sample}.R1.fastq.gz',
        r2 = 'data/{sample}.R2.fastq.gz',
        r3 = 'data/{sample}.R3.fastq.gz'
    output:
        result_folder + '/{sample}.txt'

    shell:
        'echo {input.genome} {input.r1} {input.r2} {input.r3} > {output}'

rule clean:
    shell:
        'rm results/*.txt'

rule collect_samples:
    input:
        expand(result_folder + '/{sample}.txt', sample=SAMPLES)
    output:
        result_folder + '/test.txt'
    run:
        with open(output[0], 'w') as out:
            for i in input[:-1]:
                out.write(i.split("/")[1] + ", ")
            out.write("and " + input[-1].split("/")[1] + " are successfully processed")
